[master]
    [master.university.basic_info]
    image = "image/ntust.png"
    graduate_year = 2024

    [master.university.english]
    name = "National Taiwan University of Science and Technology"
    country = "Taiwan"
    city = "Taipei"
    major = "Department of Computer Science and Information Engineering"
    description = "Big data analytics and information security"

    [master.university.chinese]
    name = "國立臺灣科技大學"
    country = "臺灣"
    city = "臺北"
    major = "資訊工程學系"
    description = "大數據分析與資訊安全"


[bachelor]
    [bachelor.university.basic_info]
    image = "image/nkust.png"
    graduate_year = 2022

    [bachelor.university.english]
    name = "National Kaohsiung University of Science and Technology"
    country = "Taiwan"
    city = "Kaohsiung"
    major = "Department of Money and Banking"

    [bachelor.university.chinese]
    name = "國立高雄科技大學"
    country = "臺灣"
    city = "高雄"
    major = "金融系"