[2023_ithome_ironman_challenge]
    [2023_ithome_ironman_challenge.basic_info]
    period_start = "2023-09"
    period_end = "2023-10"
    project_type = "personal project"
    external_link = "https://ithelp.ithome.com.tw/users/20132837/ironman/6927"
    image = "https://github.com/hsiangjenli/hsiangjenli/assets/71996166/7d0927f8-c1ea-4c11-bf7e-f3fdff670e1a"
    tags = ['Network Science', 'GNN', 'Paper Reading', '30 Days Challenge']

    [2023_ithome_ironman_challenge.english]
    project_name = "2023 IT home Ironman Challenge - AI and Data"
    # project_description = "..."

    [2023_ithome_ironman_challenge.chinese]
    project_name = "2023 IT home 鐵人賽 - AI & Data"
    # project_description = "..."

[tw_famous_ecommerce_keywords_recommendation_system]
    [tw_famous_ecommerce_keywords_recommendation_system.basic_info]
    period_start = "2023-05"
    period_end = "2023-06"
    project_type = "class project"
    image = "image/rocket.svg"
    tags = ['Graph Theory', 'Network', 'CKIP-transformer', 'Regular-Expression', 'POS-tagging', 'Fast API']

    [tw_famous_ecommerce_keywords_recommendation_system.english]
    project_name = "Graph-based : Keywords Recommendation System"
    # project_description = "..."

    [tw_famous_ecommerce_keywords_recommendation_system.chinese]
    project_name = "基於網路圖的關鍵字推薦系統"
    # project_description = "..."


[tw_famous_ecommerce_find_identical_products]
    [tw_famous_ecommerce_find_identical_products.basic_info]
    period_start = "2022-11"
    period_end = "2022-12"
    project_type = "class project"
    image = "image/rocket.svg"
    tags = ['SQLite', 'CKIP-transformer', 'Regular-Expression', 'POS-tagging', 'dimension-reduction', 'cluster']

    [tw_famous_ecommerce_find_identical_products.english]
    project_name = "Taiwan Famous Ecommerce : Find Identical Products"
    # project_description = "..."

    [tw_famous_ecommerce_find_identical_products.chinese]
    project_name = "..."
    # project_description = "..."


[apriori_j104]
    [apriori_j104.basic_info]
    period_start = "2022-05"
    period_end = "2022-06"
    project_type = "class project"
    external_link = "https://hsiangjenli.gitlab.io/apriori-j104/README.html"
    image = "https://i.imgur.com/bJS92RH.png"
    tags = ['Web Scraping', 'pyvis', 'apyori', 'CKIP-transformer']

    [apriori_j104.english]
    project_name = "Apriori J104"
    # project_description = "..."

    [apriori_j104.chinese]
    project_name = "工作技能分析系統"
    # project_description = "..."


[public_opinion_analysis]
    [public_opinion_analysis.basic_info]
    period_start = "2022-03"
    period_end = "2022-06"
    project_type = "class project"
    external_link = "https://gitlab.com/hsiangjenli/NKUST-1102-Django-POA-Midterm-Project/-/wikis/home"
    image = "image/rocket.svg"
    tags =  ['Web Scraping', 'Django', 'MongoDB', 'Bootstrap', 'plotly.js', 'Anue', 'TWSE']

    [public_opinion_analysis.english]
    project_name = "Financial Public Opinion Analysis"
    # project_description = "..."

    [public_opinion_analysis.chinese]
    project_name = "輿情分析系統"
    # project_description = "..."


[webscraping_anue]
    [webscraping_anue.basic_info]
    period_start = "2022.04"
    period_end = "2022.04"
    project_type = "personal project"
    external_link = "https://gitlab.com/tuxedo-web-scraping/anue"
    image = "https://sfiles.cnyes.cool/fe-common/dd01f09f/76bfdbe59e3e432ffe6d5d203a37e64d.svg"
    tags = ['Web Scraping', 'MongoDB']

    [webscraping_anue.english]
    project_name = "Web Scraping : Anue"

    [webscraping_anue.chinese]
    project_name = "爬蟲 : Anue"
    

[webscraping_twse]
    [webscraping_twse.basic_info]
    period_start = "2021.12"
    period_end = "2022.04"
    project_type = "personal project"
    external_link = "https://github.com/hsiangjenli/Web-Scraping-Challenge/tree/main/TWSE｜台灣證券交易所"
    image = "image/rocket.svg"
    tags = ['Web Scraping', 'SQLite', 'plotly']

    [webscraping_twse.english]
    project_name = "Web Scraping : TWSE"

    [webscraping_twse.chinese]
    project_name = "爬蟲 : 台灣證券交易所"


[linebot_stock_info]
    [linebot_stock_info.basic_info]
    period_start = "2020.10"
    period_end = "2021.07"
    project_type = "personal project"
    external_link = "https://github.com/hsiangjenli/LineBot-STOCK.tw-Public"
    image = "https://camo.githubusercontent.com/a171e8f00d35f451876bc4165e5c05a8453fc8bfa553d4df88530b5020ee175f/68747470733a2f2f692e696d6775722e636f6d2f444c524b5871372e706e67"
    tags = ['Line-Bot', 'Heroku', 'mplfinance', 'yfinance']

    [linebot_stock_info.english]
    project_name = "Line-Bot : Stock Info"

    [linebot_stock_info.chinese]
    project_name = "Line-Bot : 股票資訊"




