[Author] 
Name.English = 'Hsiang-Jen-Li'
Name.NickName = 'RN'

Name.Others.Original = '李享紝'
Name.Others.Pronunciation = 'image/李享紝.svg'

Profile = 'image/logo.svg'
Mail = 'hsiangjenli@gmail.com'

[Social_Media]
  [Social_Media.Github]
    Home = 'https://github.com/hsiangjenli'
    BG_Color = '100000'
    Logo_Color = 'white'
    Font_Awesome = 'fa-brands fa-github'

  [Social_Media.Gitlab]
    Home = 'https://gitlab.com/hsiangjenli'
    BG_Color = '330F63'
    Logo_Color = 'white'
    Font_Awesome = 'fa-brands fa-gitlab'

  [Social_Media.Kaggle]
    Home = 'https://www.kaggle.com/hsiangjenli'
    BG_Color = '20BEFF'
    Logo_Color = 'white'
    Font_Awesome = 'fa-brands fa-kaggle'

  [Social_Media.Blog]
    Home = 'https://hsiangjenli.github.io/blog'
    BG_Color = '7160b0'
    Logo_Color = 'white'
    Font_Awesome = 'fa-brands fa-blogger-b'

  [Social_Media.CheatSheets]
    Home = 'https://hsiangjenli.github.io/cheat-sheet'
    BG_Color = '3f3663'
    Logo_Color = 'white'
    Font_Awesome = 'fa-solid fa-ghost'

[Education]
  [Education.Master]
    University.Name = 'National Taiwan University of Science and Technology'
    University.Others = '國立臺灣科技大學'
    University.Country = 'Taiwan'
    University.Logo = 'image/ntust.png'
    Major.Name = 'Department of Industrial Management'
    Major.Others = '工管所（大數據與資訊安全）'
    Graduation = false

  [Education.Bachelor]
    University.Name = 'National Kaohsiung University of Science and Technology'
    University.Others = '國立高雄科技大學'
    University.Country = 'Taiwan'
    University.Logo = 'image/nkust.png'
    Major.Name = 'Department of Money and Banking'
    Major.Others = '金融系（2022）'
    Graduation = true

[Award]
  # [Award.2022_TABF_TBB_Fintech]
  # Year = '2022'
  # Name.Host = 'Taiwan Academy of Banking and Finance'
  # Name.Others = '台灣金融研訓院-臺灣中小企業銀行-校園金融科技創意挑戰賽'
  # Name.English = 'Campus Fintech Innovation Challenge'
  # Ranking = '8/187'
  # Cover = 'https://th.bing.com/th/id/R.499f30b79e79f1156a02f9745b516589?rik=aeCJCVY1AisOpA&pid=ImgRaw&r=0'

  [Award.2022_NKUST_EE_AI]
  Year = '2022'
  Name.Host = 'National Kaohsiung University of Science and Technology - Electrical Engineering'
  Name.Others = '國立高雄科技大學-電機系-人工智慧暨類神經網路聯合專題展'
  Name.English = 'Joint Exhibition on Artificial Intelligence and Neural Networks'
  Ranking = 1
  Cover = 'https://user-images.githubusercontent.com/71996166/222050262-a19f4b61-0d9a-4149-b540-528e0e03f75f.png'

  [Award.2020_FintechSpace]
  Year = '2020'
  Name.Host = 'Fintech Space'
  Name.Others = 'Fintech Space-校園成果展'
  Name.English = 'Campus Achievement Exhibition'
  Ranking = "Competition's preferred choice"
  Cover = 'https://www.fintechspace.com.tw/wp-content/uploads/2020/08/FinTechSpace-logo-%E5%BD%A9%E8%89%B2.png'

[Personal_Project]
  [Personal_Project.Rutens]
  Year = '2022'
  Name = 'Rutens'
  Tags = ['SQLite', 'CKIP-transformer', 'Regular-Expression', 'POS-tagging', 'dimension-reduction', 'cluster']
  Cover = ''

  [Personal_Project.AprioriJ104]
  Year = '2022'
  Name = 'Apriori-J104-工作技能關聯性分析'
  Tags = ['Web Scraping', 'pyvis', 'apyori', 'ckip-transformers']
  Documentation = 'https://hsiangjenli.gitlab.io/apriori-j104/README.html'
  Cover = 'https://i.imgur.com/bJS92RH.png'
  
  # [Personal_Project.FrozenFlaskPersonalBlog]
  # Year = '2022'
  # Name = 'Frozen-Flask-Personal-Blog-個人部落格'
  # Tags = ['Flask', 'Frozen-Flask', 'Bootstrap', 'gitlab page']
  # Documentation = 'https://hsiangjenli.gitlab.io/'
  # Cover = ''

  [Personal_Project.DjangoPOA]
  Year = '2022'
  Name = 'NKUST-Django-Public-Opinion-Analysis-輿情分析網頁'
  Tags = ['Web Scraping', 'Django', 'MongoDB', 'Bootstrap', 'plotly.js', 'Anue', 'TWSE']
  Documentation = 'https://gitlab.com/hsiangjenli/NKUST-1102-Django-POA-Midterm-Project/-/wikis/home'
  Cover = ''

  [Personal_Project.TWSE]
  Year = '2021'
  Name = 'TWSE-台灣證券交易所'
  Tags = ['Web Scraping']
  Documentation = 'https://github.com/hsiangjenli/Web-Scraping-Challenge/tree/main/TWSE｜台灣證券交易所'
  Cover = ''

  [Personal_Project.Anue]
  Year = '2021'
  Name = 'Anue-鉅亨網'
  Tags = ['Web Scraping', 'MongoDB']
  Documentation = 'https://gitlab.com/tuxedo-web-scraping/anue'
  Cover = 'https://sfiles.cnyes.cool/fe-common/dd01f09f/76bfdbe59e3e432ffe6d5d203a37e64d.svg'

  [Personal_Project.LineBot]
  Year = '2020'
  Name = 'LineBot-股票資訊查詢'
  Tags = ['Line-Bot', 'Heroku', 'mplfinance', 'yfinance']
  Documentation = 'https://github.com/hsiangjenli/LineBot-STOCK.tw-Public'
  Cover = 'https://camo.githubusercontent.com/a171e8f00d35f451876bc4165e5c05a8453fc8bfa553d4df88530b5020ee175f/68747470733a2f2f692e696d6775722e636f6d2f444c524b5871372e706e67'

[Skills]
  [Skills.Python]
  Title = 'Python'
  Description = 'I have extensive experience using Python for both static and dynamic web scraping, as well as building dynamic web pages using Django. I am well-versed in utilizing data analysis and machine learning packages such as Pandas, Numpy, and scikit-learn. Additionally, I am able to integrate databases through Python programming.'
  Image = 'image/python.svg'

  [Skills.Docker]
  Title = 'Docker'
  Description = 'Basic operations'
  Image = 'image/docker.svg'

  [Skills.Database]
  Title = 'Database'
  Description = 'Basic operations'
  Image = 'https://labs.mysql.com/common/logos/mysql-logo.svg?v2'

  [Skills.Ubuntu]
  Title = 'Ubuntu'
  Description = 'Basic operations'
  Image = 'data:image/svg+xml,%3C%3Fxml%20version%3D%271.0%27%20encoding%3D%27UTF-8%27%20standalone%3D%27no%27%3F%3E%0A%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20xml%3Aspace%3D%27preserve%27%20height%3D%27400px%27%20width%3D%27400px%27%20version%3D%271.1%27%20enable-background%3D%27new%20-97%20220.9%20400%20400%27%20viewBox%3D%27-97%20220.9%20400%20400%27%3E%0A%3Cstyle%20type%3D%27text%2Fcss%27%3E%0A%09.st0%7Bfill%3A%23E95420%3B%7D%0A%09.st1%7Bfill%3A%23FFFFFF%3B%7D%0A%3C%2Fstyle%3E%0A%09%3Cpath%20class%3D%27st0%27%20d%3D%27m303%20420.9c0%20110.4-89.5%20200-200%20200s-200-89.6-200-200c0-110.5%2089.5-200%20200-200s200%2089.5%20200%20200z%27%2F%3E%0A%09%09%3Cpath%20class%3D%27st1%27%20d%3D%27m-33%20394.2c-14.8%200-26.7%2012-26.7%2026.7s12%2026.7%2026.7%2026.7%2026.7-12%2026.7-26.7c0-14.8-12-26.7-26.7-26.7zm190.7%20121.3c-12.8%207.4-17.1%2023.7-9.8%2036.5%207.4%2012.8%2023.7%2017.2%2036.5%209.8s17.1-23.7%209.8-36.5c-7.5-12.7-23.8-17.1-36.5-9.8zm-132.7-94.6c0-26.4%2013.1-49.7%2033.2-63.8l-19.5-32.7c-23.4%2015.6-40.7%2039.5-48%2067.4%208.4%206.9%2013.8%2017.4%2013.8%2029.1s-5.4%2022.2-13.8%2029.1c7.2%2027.9%2024.6%2051.8%2048%2067.4l19.5-32.7c-20.1-14.1-33.2-37.4-33.2-63.8zm78-78c40.8%200%2074.2%2031.2%2077.7%2071.1l38.1-0.6c-1.9-29.4-14.7-55.8-34.5-75.2-10.2%203.8-21.9%203.2-32-2.6-10.2-5.9-16.5-15.7-18.3-26.5-9.9-2.7-20.3-4.2-31-4.2-18.5%200-35.9%204.3-51.4%2012l18.6%2033.2c9.9-4.6%2021.1-7.2%2032.8-7.2zm0%20156c-11.7%200-22.9-2.6-32.9-7.2l-18.6%2033.2c15.5%207.7%2033%2012%2051.4%2012%2010.7%200%2021.1-1.5%2031-4.2%201.7-10.7%208.1-20.6%2018.3-26.5%2010.1-5.9%2021.9-6.4%2032-2.6%2019.7-19.4%2032.6-45.8%2034.5-75.2l-38.1-0.6c-3.4%2039.8-36.8%2071.1-77.6%2071.1zm54.6-172.7c12.8%207.4%2029.1%203%2036.5-9.8s3-29.1-9.8-36.5-29.1-3-36.5%209.8c-7.3%2012.8-2.9%2029.1%209.8%2036.5z%27%2F%3E%0A%3C%2Fsvg%3E'

  [Skills.git]
  Title = 'git'
  Description = ''
  Image = 'https://git-scm.com/images/logo@2x.png'