name: 'Deploy my Static Website'

on:
  schedule: [{cron: "0 0 * * 0"}]
  push:
    branches: [html5]

jobs:
  sync:
    # ==============================================================================================================================
    name: 'Deploy my Static Website'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # ==============================================================================================================================
    steps:
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: html5
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
    # ------------------------------------------------------------------------------------------------------------------------------    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Clone repo
      run: |
        git clone https://github.com/hsiangjenli/hsiangjenli.github.io.git
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Run Python code to generate static site
      run: |
        python auto.py
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Setup Weasyprint mini Docker Image
      uses: addnab/docker-run-action@v3
      with:
          image: minidocks/weasyprint
          options: -v ${{ github.workspace }}:/app -w /app --user=root
          run: weasyprint static/output/cv_eng.html -s static/css/cv.css static/pdf/cv_eng.pdf
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Copy Static Folder
      run: cp -r static/* hsiangjenli.github.io/static/
    # ------------------------------------------------------------------------------------------------------------------------------
    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        
        cd hsiangjenli.github.io
        git branch
        git add .
        git commit -am "auto: updated by github workflow" && git pull origin main --rebase --strategy-option=ours && git push origin main|| echo "No changes to commit"