name: current year calendar
on:
  schedule: [{cron: "0 0 * * 0"}]
  push:
    branches: [readme]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
       contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.calendar.svg
        token: ${{ github.token }}
        base: ""
        plugin_calendar: yes
        plugin_calendar_limit: 2
