name: current year calendar
on:
  push:
    branches: [readme]

uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.calendar.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_calendar: yes
